version: "3.9"

volumes:
  mongodata:

services:
  booklibrary_db:
    image: mongo:${MONGO_TAG:-5.0}
    ports:
      # Port exposed as a convenience for local development
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  booklibrary_api:
    profiles: ["all"]
    image: booklibrary-go:${TAG:-latest}
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    ports:
      - "8000:8000"
    environment:
      - BOOKLIBRARY_MONGOURI=mongodb://booklibrary_db:27017
