version: "3.9"

volumes:
  mongodata:

services:
  booklibrary-db:
    image: mongo:${MONGO_TAG:-6.0}
    ports:
      # Port exposed as a convenience for local development
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  booklibrary-api:
    profiles: ["all"]
    image: booklibrary-api:${TAG:-latest}
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    ports:
      - "8000:8000"
    environment:
      - BOOKLIBRARY_MONGOURI=mongodb://booklibrary-db:27017
