version: '3'

includes:
  go: Tasks.Go.yaml
  mongo: Tasks.Mongo.yaml
  docdb: Tasks.DocumentDB.yaml
  docker: Tasks.Docker.yaml

vars:
  VERSION: 
    sh: echo "0.0.0-SNAPSHOT-$(git rev-parse --short HEAD)"
  COMMIT: 
    sh: git rev-parse HEAD
  DATE: 
    sh: date -u +%Y-%m-%dT%H:%M:%SZ
  SHA: 
    sh: git rev-parse --short HEAD

tasks:
  default:
    desc: Runs tests and builds the application
    cmds:
      - task: go:tidy
      - task: go:build
      - task: go:test
