version: "3.9"

services:
  kubeup:
    image: ${IMAGE:-kubeup}:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - KU_SENDGRID_APIKEY=${KU_SENDGRID_APIKEY}
      - KU_SENDGRID_FROM=${KU_SENDGRID_FROM}
      - KU_SENDGRID_TO=${KU_SENDGRID_TO}
      - KU_SENDGRID_SUBJECT=${KU_SENDGRID_SUBJECT}
