version: "3.9"

services:
  kubeup:
    image: ${IMAGE:-kubeup}:${TAG:-dev}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        COMMIT: ${COMMIT}
        VERSION: ${VERSION}
        DATE: ${DATE}
    ports:
      - "8000:8000"
    environment:
      - KU_EMAIL_FROM=${KU_EMAIL_FROM}
      - KU_EMAIL_TO=${KU_EMAIL_TO}
      - KU_EMAIL_SUBJECT=${KU_EMAIL_SUBJECT}
      - KU_SMTP_PORT=${KU_SMTP_PORT:-587}
      - KU_SMTP_HOST=${KU_SMTP_HOST}
      - KU_SMTP_USERNAME=${KU_SMTP_USERNAME}
      - KU_SMTP_PASSWORD=${KU_SMTP_PASSWORD}