version: '3'

tasks:
  run:
    desc: Runs the application
    cmds:
      - go run cmd/webhook/main.go -debug

  build:
    desc: Builds the application binary
    cmds:
      - go build -o webhook cmd/webhook/main.go
      
  test:
    desc: Runs the tests
    cmds:
      - go test -v ./...
  
  docker:build:
    desc: Builds the application's Docker image
    cmds:
      - docker compose build  

  docker:up:
    desc: Runs the application in Docker
    cmds:
      - docker compose up -d
  
  docker:down:
    desc: Shuts down the application running in Docker 
    cmds:
      - docker compose down
  
  docker:logs:
    desc: Streams all containers stdout/stderr (blocks, CTRL+C to exit)
    cmds:
      - docker compose logs --follow 
    ignore_error: true
